apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocene-polnilnice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocene-polnilnice
  template:
    metadata:
      labels:
        app: ocene-polnilnice
    spec:
      containers:
        - image: gs1121/ocene-polnilnice
          name: ocene-polnilnice
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: ocene-polnilnice
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: ocene-polnilnice